In [3]:
## Basics

import numpy as np
arr1 = np.arange(15).reshape(3,5)
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.dtype.name)
print(arr1.itemsize) ## size in byte of each element in the array
print(arr1.size) ## number of elements in the array
print(arr1.data)
print(type(arr1))
print(arr1.nbytes) ## 60 = 15 * 4

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
int32
4
15
<class 'numpy.ndarray'>
60


In [4]:
## Array Creation

a = np.array([1,2,3])
print(a)
print(a.dtype)
b = np.array([1.2,2.3,3])
print(b)
print(b.dtype)

c = np.array([(1,2,3),(4,5,6)])
print(c)

d = np.array([[1,2],[3,4]],dtype=complex)
print(d)

[1 2 3]
int32
[1.2 2.3 3. ]
float64
[[1 2 3]
 [4 5 6]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [5]:
e = np.zeros((3,4))
print(e)
print(e.dtype)

f = np.ones((2,3),dtype=int)
print(f)
print(f.dtype)

g = np.ones((2,3,4))
print(g)
print(g.dtype) ## By default float 64

h = np.empty((2,3))
print(h)
print(h.dtype)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
[[1 1 1]
 [1 1 1]]
int32
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
float64
[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [6]:
i = np.arange(10,40,5)
print(i)
print(i.dtype)

j = np.arange(1,5,0.3)
print(j)

k = np.linspace(1,3,8) ## linspace receives the 3rd argument as number of elements instead of step, and produce evenly spaced numbers
print(k)

l = np.linspace(4,40) ## Generates 50 evenly spaced numbers Because the default value of num (number of samples) in np.linspace is 50.
print(l)

[10 15 20 25 30 35]
int32
[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9]
[1.         1.28571429 1.57142857 1.85714286 2.14285714 2.42857143
 2.71428571 3.        ]
[ 4.          4.73469388  5.46938776  6.20408163  6.93877551  7.67346939
  8.40816327  9.14285714  9.87755102 10.6122449  11.34693878 12.08163265
 12.81632653 13.55102041 14.28571429 15.02040816 15.75510204 16.48979592
 17.2244898  17.95918367 18.69387755 19.42857143 20.16326531 20.89795918
 21.63265306 22.36734694 23.10204082 23.83673469 24.57142857 25.30612245
 26.04081633 26.7755102  27.51020408 28.24489796 28.97959184 29.71428571
 30.44897959 31.18367347 31.91836735 32.65306122 33.3877551  34.12244898
 34.85714286 35.59183673 36.32653061 37.06122449 37.79591837 38.53061224
 39.26530612 40.        ]


In [7]:
## Printing Arrays

a = np.arange(6)
print(a)

b = np.arange(12).reshape(3,4)
print(b)

c = np.arange(24)
c.reshape(2,3,4)
print(c)


[0 1 2 3 4 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [8]:
print(np.arange(10000)) ## Skips in between

print(np.arange(10000).reshape(100,100))

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [9]:
## Basic Operations

a = np.array([20,30,40,50])
b = np.arange(4)
c = a-b
print(c)

print(b**2)

print(np.sin(a))
print(np.sin(a)*10)

print(a<35)

[20 29 38 47]
[0 1 4 9]
[ 0.91294525 -0.98803162  0.74511316 -0.26237485]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a*b) ## Element-wise Product

print(a@b) ## Matrix Product

print(a.dot(b)) ## Matrix Product

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [11]:
rg = np.random.default_rng()
print(rg.integers(5)) ## produce integer less than 5 i.e.[0.5]

print(rg.integers(5,10)) ## produce in range 5 -> 9

print(rg.random()) ## Produces Floating Number

a = rg.random() ## Value changes in each Run
print(a)

1
5
0.9055764532284601
0.4871309493027861


In [12]:
rg = np.random.default_rng(1) ## Seed provides same number in each run , different seed provide different sequence of numbers
a = rg.random()
print(a)

print(rg.integers(3,7))

arr1 = rg.integers(10,100,size=20)
print(arr1)

arr2 = rg.random(10)
print(arr2)

arr3 = rg.random((2,3))##dimensions
print(arr3)

arr4 = rg.integers(5,10,size=(2,5))
print(arr4)

0.5118216247002567
6
[95 13 22 84 95 32 38 88 48 34 84 33 46 67 59 17 12 87 77 85]
[0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299
 0.20345524 0.26231334 0.75036467 0.28040876]
[[0.48519097 0.9807372  0.96165719]
 [0.72478994 0.54122686 0.2768912 ]]
[[7 8 5 6 9]
 [7 7 6 5 7]]


In [13]:
rg = np.random.default_rng(3)

a = np.ones((2,3),dtype=int)
print(a)

b = rg.random((2,3))
print(b)

b+= a
print(b)

# a += b -> float result cannot be stored in int array
# print(a)

[[1 1 1]
 [1 1 1]]
[[0.08564917 0.23681051 0.80127447]
 [0.58216204 0.09412864 0.43312694]]
[[1.08564917 1.23681051 1.80127447]
 [1.58216204 1.09412864 1.43312694]]


In [14]:
a = np.ones(3,dtype=int)
print(a)
b = np.linspace(0,np.pi,3)
print(b)
c=a+b
print(c)
print(c.dtype)
d = np.exp(c*1j)
print(d)
print(d.dtype)

[1 1 1]
[0.         1.57079633 3.14159265]
[1.         2.57079633 4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [15]:
arr = rg.random((2,3))
print(arr)
print(arr.sum())
print(arr.min())
print(arr.max())

[[0.4790513  0.15973891 0.73457715]
 [0.11367202 0.39122819 0.51674018]]
2.395007757225556
0.11367201992140341
0.7345771514092145


In [16]:
arr = np.arange(12).reshape(3,4)
print(arr)

print(arr.sum(axis=0)) ## Sum of each column
print(arr.sum(axis=1)) ## Sum  of Each Row

print(arr.min(axis=1)) ## min in each row
print(arr.max(axis=0)) ##max in each column

print(arr.cumsum(axis=0)) ## cummulative sum along column
print(arr.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
[0 4 8]
[ 8  9 10 11]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [17]:
## Universal Functions

a = np.arange(3)
print(a)
print(np.exp(a)) ## Produces e^x , where x is elements in the array
print(np.sqrt(a))
c = np.array([2.,-1.,4.])
print(np.add(a,c))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


In [18]:
## Indexing Slicing & Iterating

a = np.arange(10)**3
b = np.arange(10)**3
print(a)
print(a[3])
print(a[1:5])
print(a[:1]) # Prints elements upto index specified (excluding)
print(a[1:]) # Prints from the index specified
a[:6:2] = 1000 # Set every 2nd element to 1000 upto index specified (excluding)
print(a)
a=b # It is not creating a copy , it makes both variables point to what b points to
a[3::3] = 1000 # Set every 3nd index to 1000 from the index specified
print(a)
a[4:6] = 1000 # Set all index from 4 to index less than 6 as 1000
print(a)
print(a[::-1]) # Reverse

[  0   1   8  27  64 125 216 343 512 729]
27
[ 1  8 27 64]
[0]
[  1   8  27  64 125 216 343 512 729]
[1000    1 1000   27 1000  125  216  343  512  729]
[   0    1    8 1000   64  125 1000  343  512 1000]
[   0    1    8 1000 1000 1000 1000  343  512 1000]
[1000  512  343 1000 1000 1000 1000    8    1    0]


In [19]:
a = np.arange(10)**3
print(a)
for num in a:
    print (num)

[  0   1   8  27  64 125 216 343 512 729]
0
1
8
27
64
125
216
343
512
729


In [ ]:
def f(x,y):
    return 10*x+y

arr = np.fromfunction(f,(5,4),dtype=int) ## calls function f for each co-ordinates
print(arr)
print(arr[2,3])
print(arr[2][3])
print(arr[1:5]) ## Prints from 2nd to 5th row
print(arr[2:]) ##Prints from 3rd row
print(arr[:3]) ##Prints upto 3rd row
print(arr[0:5][1]) ## selects rows from 0 to 4 and then from those rows it chooses the 1st row
print(arr[0:5,1]) ## using tuple -> select row from 0 to 4 and then from it chooses the 1st column
print(arr[:,1]) ## same as previous one
print(arr[1:3,:]) ## select rows from 1,2 and then chooses all coumns in it
print(arr[3]) ##When fewer indices are provided than the number of axes, the missing indices are considered complete slices: equivalent to : arr[3,:]
print(arr[-1]) ## Print last row , equivalent to -> arr[-1,:]
print(arr[:,0:3:2]) ## selects all rows , startindex:endindex:step 

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
23
[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[[20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
[10 11 12 13]
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[30 31 32 33]
[40 41 42 43]
[[ 0  2]
 [10 12]
 [20 22]
 [30 32]
 [40 42]]


In [21]:
a = np.array([[[0,1,2],[10,11,12]],[[100,101,102],[110,112,113]]])
print(a.ndim)
print(a.shape)

print(a[1])
print(a[1,:,:])
print(a[1,...])

print(a[0,:,2])

print(a[...,2]) ## Equivalent to a[:,:,2]

for r1 in a:
    for r2 in r1:
        print(r2)

for num in a.flat: ## flat attribute which is an iterator over all elements of the array
    print(num)

3
(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[100 101 102]
 [110 112 113]]
[[100 101 102]
 [110 112 113]]
[ 2 12]
[[  2  12]
 [102 113]]
[0 1 2]
[10 11 12]
[100 101 102]
[110 112 113]
0
1
2
10
11
12
100
101
102
110
112
113
