In [20]:
## Changing the shape of an array
import numpy as np
rg = np.random.default_rng(1)
a = rg.integers(1,13,size=(3,4))
print(a)
print(a.shape)

[[ 6  7 10 12]
 [ 1  2 10 12]
 [ 3  4 11  6]]
(3, 4)


In [ ]:
## the following three commands all return a modified array, but do not change the original array

print(a.ravel()) ## reval() -> Returns array element as flattened 
print(a)
print(a.reshape(4,3)) ## Returns with modified shape
print(a)
print(a.T) ## Returns Transpose
print(a)

[ 6  7 10 12  1  2 10 12  3  4 11  6]
[[ 6  7 10 12]
 [ 1  2 10 12]
 [ 3  4 11  6]]
[[ 6  7 10]
 [12  1  2]
 [10 12  3]
 [ 4 11  6]]
[[ 6  7 10 12]
 [ 1  2 10 12]
 [ 3  4 11  6]]
[[ 6  1  3]
 [ 7  2  4]
 [10 10 11]
 [12 12  6]]
[[ 6  7 10 12]
 [ 1  2 10 12]
 [ 3  4 11  6]]


In [24]:
print(a)
print(a.resize(2,6)) ## Modifies the array itself with the size mentioned and returns 'None'.
print(a)

print(a.reshape(3,-1)) ##If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated
print(a)
print(a.reshape(-1))
print(a.reshape(12,-1))

[[ 6  7 10 12  1  2]
 [10 12  3  4 11  6]]
None
[[ 6  7 10 12  1  2]
 [10 12  3  4 11  6]]
[[ 6  7 10 12]
 [ 1  2 10 12]
 [ 3  4 11  6]]
[[ 6  7 10 12  1  2]
 [10 12  3  4 11  6]]
[ 6  7 10 12  1  2 10 12  3  4 11  6]
[[ 6]
 [ 7]
 [10]
 [12]
 [ 1]
 [ 2]
 [10]
 [12]
 [ 3]
 [ 4]
 [11]
 [ 6]]


In [26]:
## Stacking together different Arrays
b = rg.integers(1,6,size=(2,2))
c = rg.integers(1,5,size=(2,2))
print(b)
print(c)
print(np.vstack((b,c)))
print(np.hstack((b,c)))

[[5 4]
 [5 3]]
[[4 2]
 [2 4]]
[[5 4]
 [5 3]
 [4 2]
 [2 4]]
[[5 4 4 2]
 [5 3 2 4]]


In [68]:
rg = np.random.default_rng(1)
f = np.array([[1,2,3],[4,5,6]])
g = np.array([[7,8],[10,11]])
print(np.hstack((f,g))) ## Dimensions Conditions for hstack -> (n, a)  and  (n, b)  →  (n, a+b)

h = np.array([1,2,3])
i = np.array([[4,5,6],[7,8,9]])
print(np.vstack((h,i))) ## Dimensions Consitions for vstack -> (a, n)  and  (b, n)  →  (a+b, n)

m = rg.integers(1,10,size=(2,2,4))
n = rg.integers(1,10,size=(2,3,4))
print(np.hstack((m,n))) ## 3d hstack

o = rg.integers(1,10,size=(2,4,3))
p = rg.integers(1,10,size=(2,4,3))
print(np.vstack((o,p))) ## 3d vstack

## hstack,vstack are applicable to 4d,5d ... arrays , but only axis could have variable values

[[ 1  2  3  7  8]
 [ 4  5  6 10 11]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[5 5 7 9]
  [1 2 8 9]
  [6 5 1 1]
  [8 7 8 5]
  [8 3 5 8]]

 [[3 3 8 4]
  [3 8 3 4]
  [2 3 2 5]
  [9 2 4 4]
  [9 2 5 3]]]
[[[1 7 1]
  [3 5 5]
  [2 9 7]
  [9 1 7]]

 [[3 5 9]
  [3 7 2]
  [3 9 4]
  [5 3 2]]

 [[4 6 5]
  [7 4 6]
  [7 9 4]
  [1 7 5]]

 [[8 5 4]
  [1 5 6]
  [7 8 2]
  [6 8 3]]]


In [52]:
d = np.array([1,2,3])
e = np.array([4,5,6])
## Column stack for 1d arrays
print(np.column_stack((d,e))) ## Converts 1D arrays into coulms of 2D array.

## column stack for 2d arrays works like hstack
## coulmn stack is not applicable for 3d,4d... kind of arrays
j = np.array([[1,2],[3,4]])
k = np.array([[5,6],[7,8]])
print(np.column_stack((j,k)))
l = np.array(([9,10],[11,12]))
print(np.column_stack((j,k,l)))


[[1 4]
 [2 5]
 [3 6]]
[[1 2 5 6]
 [3 4 7 8]]
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [80]:
## Splitting one array into several ones
rg = np.random.default_rng(1)
q = rg.integers(1,11,size=(2,12))
print(q)
print(np.hsplit(q,3)) ## splits the array into 3 equal parts, but only if it’s possible.

print(np.hsplit(q,(2,5))) ## splits the array at column indices 2 and 5.

[[ 5  6  8 10  1  2  9 10  3  4  9  5]
 [ 3  9  3  5  7  6  1  1  9  8  9  6]]
[array([[ 5,  6,  8, 10],
       [ 3,  9,  3,  5]], dtype=int64), array([[ 1,  2,  9, 10],
       [ 7,  6,  1,  1]], dtype=int64), array([[3, 4, 9, 5],
       [9, 8, 9, 6]], dtype=int64)]
[array([[5, 6],
       [3, 9]], dtype=int64), array([[ 8, 10,  1],
       [ 3,  5,  7]], dtype=int64), array([[ 2,  9, 10,  3,  4,  9,  5],
       [ 6,  1,  1,  9,  8,  9,  6]], dtype=int64)]


In [ ]:
## np.array_split() splits an array into parts even when equal division is NOT possible.

r = np.arange(11)
print(r.size)
print(11//3)
print(np.array_split(r,3)) ## 11%3 -> rem = 2 , so 2 subarrays will have 1 element extra each than quotient.

11
3
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]
