In [16]:
## Np copy at all
import numpy as np
a = np.arange(12)
b=a ## no new object is created, a and b are two names for the same ndarray object
print(b is a)
print(id(a))# id is a unique identifier of an object

True
1834216654480


In [ ]:
## View or Shallow Copy
## A view is a NumPy array that shares the same data (memory) as another array.
c = a.view()
print(c is a)
print(c.flags.owndata)##tells you whether the array c owns its data or is just a view of another array.

## reshape() returns a new array object that is usually a view of the original data (not a copy).
a = np.arange(12)
print(a)
d = a.reshape(2,6)
print(d)
print(a)
d[0][0]=999
print(a)
a[1] = 77
print(d)

False
False
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[999   1   2   3   4   5   6   7   8   9  10  11]
[[999  77   2   3   4   5]
 [  6   7   8   9  10  11]]


In [ ]:
## Slicing also returns view

e = np.arange(12)
print(e)
f = e[1:4]
print(f)
f[:]=100 ##Assigns 100 to every element of the array or view
print(e)

g = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
h = g[:,1:3]
print(h)
h[:] = 999
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 2 3]
[  0 100 100 100   4   5   6   7   8   9  10  11]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[  1 999 999   4]
 [  5 999 999   8]
 [  9 999 999  12]]


In [40]:
## Deep Copy
i = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
j = i.copy()
print(j is i)
print(j.base is i) ## j.base points to the original array that owns the data
j[0][0] = 99
print(j)
print(i)

## If big is not required but a small portion of it is required
k = np.arange(1000)
l = k[:100].copy()
print(l)
del k
## print(k)

False
False
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
