In [2]:
## Indexing with Arrays of Indices
import numpy as np
a = np.arange(12)**2 
print(a)
b = np.array([1,1,3,11,9])
print(a[b])

c = np.array([[2,3],[4,7]]) ##  When you index an array with another array, NumPy treats the index array as a list of positions, not as a shape matcher.
print(a[c]) ## The shape of the index array only decides the shape of the output,

[  0   1   4   9  16  25  36  49  64  81 100 121]
[  1   1   9 121  81]
[[ 4  9]
 [16 49]]


In [5]:
palette = np.array([[0,0,0], ##black
                    [255,0,0], ##red
                    [0,255,0], ##green
                    [0,0,255], ##blue
                    [255,255,255]]) ##white
image = np.array([[0,1,2,3],[1,3,2,0]])
print(palette[image])

[[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255   0   0]
  [  0   0 255]
  [  0 255   0]
  [  0   0   0]]]


In [ ]:
## Giving indeices for more than one dimensions

d = np.arange(12).reshape(3,4)
print(d)

e = np.array([1,2])
f = np.array([3,3])



print(d[e,f]) ## Both should have same dimensions
print(d[(e,f)]) ## In Python, arr[i, j] is exactly the same as arr[(i, j)]—so we can put i and j in a tuple and then do the indexing with that

#print(d[[e,f]]) ## However, we can not do this by putting e and f into an array, because this array will be interpreted as indexing the first dimension of a.
print(d[[2,1],[2,1]])

g = np.array([[1,2],[2,1]])
h = np.array([[1,3],[3,0]])
print(d[g,h]) ## Both should have same dimensions

print(d[g,2])

print(d[:,2])

print(d[:,h]) ## Selects all rows and apply 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 7 11]
[ 7 11]
[10  5]
[[ 5 11]
 [11  4]]
[[ 6 10]
 [10  6]]
[ 2  6 10]
[[[ 1  3]
  [ 3  0]]

 [[ 5  7]
  [ 7  4]]

 [[ 9 11]
  [11  8]]]


In [ ]:
## Indexing with arrays as a target to assign

i = np.arange(5)
i[[1,2,3]] = 9
print(i)
i[[0,1,2,0]] = [1,2,3,4] ## when same index is repeated , assignment is repeated and last assigned value is stored
print(i)

i[[0,0,1]] += 1 ## For index 0 , only one time 1 is added
print(i)

[0 9 9 9 4]
[4 2 3 9 4]
[5 3 3 9 4]


In [ ]:
time = np.linspace(20,145,5)
print(time)

data = np.sin(np.arange(20)).reshape(5,4)
print(data)

ind = data.argmax(axis=0) ## argmax returns index of max value , axis=0 indicates column wise
print(ind)

time_max = time[ind]
print(time_max)

data_max = data[ind,range(data.shape[1])] ## data.shape[1] -> returns number of columns
print(data_max)

print(np.all(data_max == data.max(axis=0))) ## data_max == data.max(axis=0) -> returns a boolean array , np.all() -> returns true if all are true

[ 20.    51.25  82.5  113.75 145.  ]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 82.5   20.   113.75  51.25]
[0.98935825 0.84147098 0.99060736 0.6569866 ]
True


In [13]:
## Indexing with Boolean Arrays

j = np.arange(12).reshape(3,4)
k = j > 4
print(k)
print(j[k])

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]


In [23]:
l = np.arange(12).reshape(3,4)
print(l)
b1 = np.array([False,True,True])
b2 = np.array([True,False,True,False])

print(l[b1,:]) ## the boolean array length should be equal to number of rows

print(l[:,b2]) ## the boolean array length should be equal to number of columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [ ]:
## The ix_() Function

## Main Purpose of np.ix_() Function
## Imagine a situation where we need submatrix of a matrix , we only only which rows and clumns we need , rows -> 1,3 columns -> 2,3 ,
## so np.ix_([1,3],[2,3]) returns two arrays just changing dimension , like [[1],[3]] -> dim -> 2,1 and [[2,3]] -> dim -> 1,2
## Numpy broadcasting rul say that (2,1)(1,2) -> result will be (2,2) , so the required submatrix is got
## If we didn't use this , array[[1,3],[2,3]] will make element wise comparison and result give only two element on indices (1,2) & (3,3)


## Without np.ix_(), NumPy pairs indices element-wise.
## With np.ix_(), NumPy selects all combinations of row and column indices.
## np.ix_() is an indexing helper, not a math function.
## Its purpose is to prepare index arrays so NumPy can select all combinations (Cartesian product) of indices when indexing an array.
p = np.arange(16).reshape(4,4)
print(p)

q = np.array([1,3])
r = np.array([2,3])

s = np.ix_(q,r) ## s is a tuple of numpy arrays
print(s)
print(type(s))
print(s[0].shape) ## (2,1) this is dimension of row array -> array([[1],[3]]),
print(s[1].shape) ## (1,2) this is dimension of column array -> array([[2, 3]])

print(p[s]) ## prints actual elements 

ax , bx = np.ix_(q,r)
result = ax+bx 
## ax is [[1],[3]] which is 2*1 , bx is [[2,3]] which is 1*2 , to perform ax + bx we need 2*2 + 2*2 , so both are expanded as [[1,1],[3,3]],[[2,3],[2,3]]
## values are repeated rowise and column wise , now element wise ax+bx is done that is[[3,4],[5,6]]
print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(array([[1],
       [3]]), array([[2, 3]]))
<class 'tuple'>
(2, 1)
(1, 2)
[[ 6  7]
 [14 15]]
[[3 4]
 [5 6]]


In [22]:
m = np.array([2,3,4,5])
n = np.array([8,5,4])
o = np.array([5,4,6,8,3])

ax,bx,cx = np.ix_(m,n,o)
print(ax)
print(ax.shape)
print(bx.shape)
print(cx.shape)

result = ax + bx *cx
print(result)

print(result[3,2,4])
print(m[3]+n[2]*o[4])

[[[2]]

 [[3]]

 [[4]]

 [[5]]]
(4, 1, 1)
(1, 3, 1)
(1, 1, 5)
[[[42 34 50 66 26]
  [27 22 32 42 17]
  [22 18 26 34 14]]

 [[43 35 51 67 27]
  [28 23 33 43 18]
  [23 19 27 35 15]]

 [[44 36 52 68 28]
  [29 24 34 44 19]
  [24 20 28 36 16]]

 [[45 37 53 69 29]
  [30 25 35 45 20]
  [25 21 29 37 17]]]
17
17


In [4]:
## Automatic Reshaping

t = np.arange(30)
u = t.reshape((2,-1,3)) ## -1 means "whatever is required"
print(u.shape)
print(u)

(2, 5, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [8]:
## Vector Stacking

v = np.arange(0,10,2)
w = np.arange(5)
x = np.vstack((v,w))
print(x)
y = np.hstack([v,w])
print(y)

[[0 2 4 6 8]
 [0 1 2 3 4]]
[0 2 4 6 8 0 1 2 3 4]
