In [1]:
import numpy as np
a = np.arange(1,13).reshape(2,6)
print(a)
a[:,2] = [95,99]
print(a)

b = np.arange(1,9).reshape(2,2,2)
print(b)
b[:,1,:] = 99
print(b)

b[:,0,:] = [66,65]
print(b)

b[0,:,:] = [44,45],[46,47]
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2 95  4  5  6]
 [ 7  8 99 10 11 12]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[ 1  2]
  [99 99]]

 [[ 5  6]
  [99 99]]]
[[[66 65]
  [99 99]]

 [[66 65]
  [99 99]]]
[[[44 45]
  [46 47]]

 [[66 65]
  [99 99]]]


In [13]:
c = np.full((2,2),97)
print(c)

b = np.full_like(b,4)
print(b)

[[97 97]
 [97 97]]
[[[4 4]
  [4 4]]

 [[4 4]
  [4 4]]]


In [ ]:
## Random Decimal Numbers

d = np.random.rand(4,2)
print(d)

## Random Integer Values

e = np.random.randint(5) ## values from 0 to 4
print(e)

f = np.random.randint(5,size=(4,2))
print(f)

g = np.random.randint(-4,4,size=(3,3))
print(g)

h = np.identity(4) , ## Creates an identity matrix
print(h)

[[0.36791255 0.60583006]
 [0.72021123 0.58931201]
 [0.2600543  0.58846852]
 [0.80641317 0.00946597]]
1
[[0 1]
 [4 0]
 [0 4]
 [4 1]]
[[ 0 -3 -3]
 [ 1 -2  1]
 [ 3 -1 -2]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
## Repeat an array

i = np.array([1,2,3])
j = np.repeat(i,3)
print(j)

k = np.array([[1,2,3]])
l = np.repeat(k,4,axis=0)
print(l)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
## Pattern Printing

m = np.ones((5,5))
print(m)
n = np.zeros((3,3))
print(n)
n[1][1] = 9
print(n)

m[1:4,1:4] = n ## Instead of 4 , we can also use -1 which indicates last
print(m)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
## Linear Algebra

a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [ ]:
## Finding Determinent 

c = np.identity(3)
print(np.linalg.det(c)) ## determinent of identity matrix is 1.

1.0


In [14]:
## Statistics

a = np.arange(1,7).reshape(2,3)
print(a)
print(np.min(a))
print(np.max(a))
print(np.min(a,axis=1))
print(np.min(a,axis=0))
print(np.sum(a))
print(np.sum(a,axis=1))

[[1 2 3]
 [4 5 6]]
1
6
[1 4]
[1 2 3]
21
[ 6 15]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b,b,a))) ## vstack takes one argument () which can hold multiple arrays

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [1 2 3]]


In [41]:
## Accessing Data from a file
a = np.genfromtxt('data.txt',delimiter=',')
print(a)
a = a.astype('int32')
print(a)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [42]:
## Boolean Masking & Advanced Indexing

print(a > 15)
print(a[a>15])

print(np.any(a>15,axis=0)) ## checking whether any one value in a  column has a value greater than 15
print(np.all(a>15,axis=0)) ## Checks whether all element in a array is greater than 15

print((a>=15) & (a<=20))



[[False False False False False False False False False False]
 [False False False False False  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[ True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False]
[[False False False False False False False False False False]
 [False False False False  True  True  True  True  True  True]
 [False False False False False False False False False False]]


In [ ]:
## Indexing with list in Numpy

a = np.arange(1,10)
print(a)
print(a[[1,3,-1]])

In [ ]:
a = np.arange(1,37).reshape(6,6)
print(a)

## middle 2 rows 1st two elements
print(a[[2,3],[0,1]])

## diagonal from 2 element in 1st row
print(a[(0,1,2,3,4),(1,2,3,4,5)]) ## we can use either () or []

## print last 2 elementa form 1st , last 2 rows
print(a[[0,4,5],4:]) ## Inside list we cannot place : (slicing) , we can have integers or list or array of integers

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[13 20]
[ 2  9 16 23 30]
[[ 5  6]
 [29 30]
 [35 36]]
