In [4]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
## Np array are faster and memory efficient than python
import sys
arr2 = range(1000)
print(sys.getsizeof(5)*len(arr2)) # A typical Python int takes 28 bytes on a 64-bit system.

arr3 = np.arange(1000)
print(arr3.itemsize*arr3.size) # On many systems, NumPy uses int32 → 4 bytes per element

28000
4000


In [ ]:
# -> Fast
import time
import numpy as np
size = 1000
l1 = range(size)
l2 = range(size)
start = time.time()
result1 = [(x+y) for x,y in zip(l1,l2)]
print("Python list took : ",(time.time()-start)*1000) # multiplying by 1000 changes seconds to milliseconds
n1 = np.arange(size)
n2 = np.arange(size)
start = time.time()
result2 = n1+n2
print("Numpy Array took : ",(time.time()-start)*1000)


Python list took :  1.0921955108642578
Numpy Array took :  0.0


In [ ]:
import numpy as np
n1 = np.array([1,2,3,10])
n2 = np.array([4,5,6,3])
print(n1+n2)
print(n2-n1)
print(n1-n2)
print(n1*n2)
print(n1/n2)

[5 7 9]
[3 3 3]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [12]:
import numpy as np
n1 = np.array([4,5,6])
print(n1[0])
# Multi Dimensional Array
n2 = np.array([[1,2,3],[4,5,6]])
print(n2)

print(n2.ndim) # Gives dimensions of the array

4
[[1 2 3]
 [4 5 6]]
2
